### ISSUE TITLE
resort

### ISSUE THREAD

**Issue by tuwan1214** [yuhuan-wu/P2T#18] opened 2023-09-11 08:35 UTC
Hello author, I would like to know what the configuration of the P2P environment you are using is because I may encounter some bugs during my own configuration, which is why I want to know

**Comment by yuhuan-wu** [comment] 2023-09-11 09:24
I used timm == 0.3.2, torch==1.7.0 to do this work. Higher versions also work for testing, but I am not sure if you can reproduce it in the training stage (ImageNet). 

Could you tell me the environments you are using?

**Comment by tuwan1214** [comment] 2023-09-11 10:13
My environment is timm==0.3.2 torch==1.9 mmcv-full==1.4.0 mmsegmentation==0.13.0 I don't know if this will have any effect on the use of p2t


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuhuan-wu/P2T"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuhuan-wu/P2T] resort (Issue #18)





 
I used timm == 0.3.2, torch==1.7.0 to do this work. Higher versions also work for testing, but I am not sure if you can reproduce it in the training stage (ImageNet).
 
Could you tell me the environments you are using?

**Comment by yuhuan-wu** [comment] 2023-09-11 10:28
It seems the environment is OK. If possible, could you paste the error logs here?

**Comment by tuwan1214** [comment] 2023-09-12 05:02
The other versions I tried before had some issues to some extent, but now the problem I am encountering is that the pre training file is not a checkpoint file. I will import the downloaded pre training file path, but I still have this issue.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuhuan-wu/P2T"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 晚上6:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuhuan-wu/P2T] resort (Issue #18)





 
It seems the environment is OK. If possible, could you paste the error logs here?

**Comment by tuwan1214** [comment] 2023-09-12 06:54
I have encountered this problem many times and I am not sure if it is a bug. TypeError: object of type 'int' has no len(). The specific problem is shown in the figure below. I would like to ask if you have encountered similar problems before.










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuhuan-wu/P2T"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 晚上6:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuhuan-wu/P2T] resort (Issue #18)





 
It seems the environment is OK. If possible, could you paste the error logs here?

**Comment by yuhuan-wu** [comment] 2023-09-14 07:23
**Please specify where the error is**. Besides, I did not see the figure you mentioned. If you do not give enough details, I cannot assist to solve the bug further.

**Comment by yuhuan-wu** [comment] 2023-09-19 01:16
Since we do not know where the issue is without any response, we would like to close this issue.

**Closed as completed by yuhuan-wu** 2023-09-19 01:16 UTC

**Comment by tuwan1214** [comment] 2023-09-20 04:55
Thank you very much for your willingness to help me. I guess it may be that the multi-card training strategy is used in the source code, and my server is a single card, so I would like to ask you what changes you need to make for single-card training.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuhuan-wu/P2T"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 上午9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuhuan-wu/P2T] resort (Issue #18)





 
Since we do not know where the issue is without any response, we would like to close this issue.

**Comment by yuhuan-wu** [comment] 2023-09-22 17:04
If you have troubles on adapting P2T to other repositories. I recommend you to see this project: https://github.com/yuhuan-wu/EDN/tree/master
